import { pathToFileURL } from 'node:url';
import { returnToExplore, setConfiguredLevel } from './journey_level_session_harness.mjs';
const { webkit, devices } = await import(pathToFileURL(process.env.PLAYWRIGHT_PATH).href);
const baseUrl = process.argv[2];
const sha = process.argv[3];
if (!baseUrl || !sha) throw new Error('usage: smoke <url> <sha>');
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
async function records(page){return page.locator('flt-semantics').evaluateAll((nodes)=>nodes.map((n,index)=>{const r=n.getBoundingClientRect();return{index,role:n.getAttribute('role')||'',text:[n.getAttribute('aria-label'),n.textContent].filter(Boolean).join(' ').replace(/\s+/g,' ').trim(),disabled:n.getAttribute('aria-disabled')==='true',x:r.x,y:r.y,width:r.width,height:r.height,visible:r.width>0&&r.height>0};}));}
async function find(page,needle,{role,exact=false,timeout=15000}={}){const end=performance.now()+timeout;while(performance.now()<end){const f=(await records(page)).filter(x=>x.visible&&(!role||x.role===role)&&(exact?x.text===needle:x.text.includes(needle))).sort((a,b)=>a.width*a.height-b.width*b.height)[0];if(f)return f;await sleep(80);}throw new Error(`visible state missing: ${needle}`);}
async function tap(page,text,options={}){let lastError;for(let attempt=0;attempt<5;attempt++){const x=await find(page,text,{...options,role:'button'});if(x.disabled)throw new Error(`disabled: ${text}`);try{await page.locator('flt-semantics').nth(x.index).tap({timeout:4000});return;}catch(error){lastError=error;const message=String(error);if(!/detached|Timeout/i.test(message))throw error;await sleep(100);}}throw new Error(`${text}: tap failed after Flutter semantics refresh: ${String(lastError)}`);}
async function advanceVocabulary(page){for(let i=0;i<20;i++){const rs=await records(page);const done=rs.find(x=>x.visible&&x.role==='button'&&x.text.includes('完成并收起'));if(done){await tap(page,'完成并收起');break;}const next=rs.find(x=>x.visible&&x.role==='button'&&x.text.includes('下一个单词'));if(next){await tap(page,'下一个单词');await sleep(60);continue;}await sleep(80);}await tap(page,'继续');await find(page,'3/5',{timeout:3000});await tap(page,'继续');await find(page,'4/5',{timeout:3000});}
async function openStory(page,level,title){await page.goto(`${baseUrl}/?unlock=all&prototype=journeys&v=${sha}`,{waitUntil:'domcontentloaded',timeout:60000});const ph=page.locator('flt-semantics-placeholder').first();await ph.waitFor({state:'attached',timeout:60000});await ph.evaluate(n=>n.click());await page.locator('flt-semantics').first().waitFor({state:'attached',timeout:30000});await setConfiguredLevel(page,level);await returnToExplore(page);await tap(page,'护照');await tap(page,'中国',{exact:true});await tap(page,'北京市',{exact:true});await tap(page,'故宫博物院');await find(page,'交接前的标记');await find(page,'两条路，一张图');await tap(page,title);await find(page,'1/5');const narration=(await records(page)).filter(x=>x.visible&&x.role==='button'&&x.text.includes('开始朗读')).sort((a,b)=>a.width*a.height-b.width*b.height)[0];if(!narration)throw new Error('narration control missing');await page.touchscreen.tap(narration.x+narration.width*.535,narration.y+Math.min(22,narration.height/2));await find(page,'正在朗读');const started=performance.now();await tap(page,'继续');await find(page,'下一个单词',{timeout:3000}).catch(()=>find(page,'完成并收起',{timeout:3000}));const wordDetailMs=performance.now()-started;if(wordDetailMs>=3000)throw new Error(`${title} Lv${level} Word Detail ${wordDetailMs}ms`);await advanceVocabulary(page);return wordDetailMs;}
const browser=await webkit.launch({headless:true});const results=[];const specs=[1,5,6,7,10].map(level=>({level,title:'交接前的标记'})).concat([{level:6,title:'两条路，一张图'}]);for(const spec of specs){const context=await browser.newContext({...devices['iPhone 13 Pro Max']});await context.addInitScript(()=>{class U extends EventTarget{constructor(text){super();this.text=text;this.lang='';this.rate=1;this.pitch=1;this.volume=1;}}const synth={speaking:false,pending:false,paused:false,getVoices:()=>[],speak(u){this.speaking=true;setTimeout(()=>u.dispatchEvent(new Event('start')),0);},cancel(){this.speaking=false;},pause(){this.paused=true;},resume(){this.paused=false;this.speaking=true;}};Object.defineProperty(window,'SpeechSynthesisUtterance',{configurable:true,value:U});Object.defineProperty(window,'speechSynthesis',{configurable:true,value:synth});});const page=await context.newPage();results.push({...spec,wordDetailMs:await openStory(page,spec.level,spec.title)});await context.close();}await browser.close();console.log(`FOUNDER_PREVIEW_WEBKIT_SMOKE ${JSON.stringify({sha,results})}`);
