name = "phoenix-journeys-alpha"
main = "./worker/index.mjs"
compatibility_date = "2026-07-17"

[assets]
directory = "./app/build/web"
not_found_handling = "single-page-application"
binding = "ASSETS"
run_worker_first = [ "/api/*" ]

[ai]
binding = "AI"
