import test from 'node:test';
import assert from 'node:assert/strict';
import { buildLiveIdentity, assertEvidenceFresh } from '../src/identity-freshness.mjs';
import { createTrustedEvidenceManifest, validateEvidenceManifest } from '../src/evidence-authority.mjs';
import { assertPhaseAActions, assertPrincipalSeparation, validateFounderAuthorization, candidateGateClaims } from '../src/authority-enforcement.mjs';
const sha=c=>c.repeat(40), dig=c=>c.repeat(64);
const id={repository:'o/r',pr_number:148,base_branch:'main',base_sha:sha('a'),candidate_sha:sha('b'),candidate_tree:sha('c'),task_contract_digest:dig('d'),governance_body_digest:dig('e'),workflow_run_id:'10',run_attempt:1};
const manifest=o=>({...createTrustedEvidenceManifest({identity:id,requiredTypes:['repo'],entries:[{evidence_id:'e',evidence_type:'repo',source:'trusted',candidate_sha:id.candidate_sha,base_sha:id.base_sha,task_contract_digest:id.task_contract_digest,result:'PASS',evidence_level:'VERIFIED',limitations:'deterministic'}],producedAt:'2026-08-05T00:00:00Z'}),...o});
const now=new Date('2026-08-05T01:00:00Z');
for(const [name,key,value] of [['PR Body edit','governance_body_digest',dig('f')],['Base retarget','base_branch','release'],['Base advance','base_sha',sha('d')],['Candidate SHA edit','candidate_sha',sha('d')],['no-op Commit','candidate_sha',sha('e')],['rerun attempt','run_attempt',2],['old Artifact reuse','workflow_run_id','11']]) test(`${name} invalidates PASS`,()=>assert.throws(()=>assertEvidenceFresh(id,{...id,[key]:value}),/EVIDENCE_STALE/));
test('Missing Evidence Manifest blocks',()=>assert.throws(()=>validateEvidenceManifest(null,{identity:id,requiredTypes:['repo'],now}),/REQUIRED/));
test('Malformed Manifest blocks',()=>assert.throws(()=>validateEvidenceManifest({trust_class:'TRUSTED_RUNNER_GENERATED',evidence:[]},{identity:id,requiredTypes:['repo'],now}),/EMPTY/));
test('Wrong Head evidence blocks',()=>assert.throws(()=>validateEvidenceManifest(manifest({candidate_sha:sha('d')}),{identity:id,requiredTypes:['repo'],now}),/candidate_sha/));
test('Wrong Base evidence blocks',()=>assert.throws(()=>validateEvidenceManifest(manifest({base_sha:sha('d')}),{identity:id,requiredTypes:['repo'],now}),/base_sha/));
test('Wrong Task Contract digest blocks',()=>assert.throws(()=>validateEvidenceManifest(manifest({task_contract_digest:dig('f')}),{identity:id,requiredTypes:['repo'],now}),/task_contract_digest/));
test('Future timestamp blocks',()=>assert.throws(()=>validateEvidenceManifest(manifest({produced_at:'2026-08-06T00:00:00Z'}),{identity:id,requiredTypes:['repo'],now}),/FUTURE/));
test('Builder and Auditor same principal blocks',()=>assert.throws(()=>assertPrincipalSeparation([{execution_principal_id:'p',role:'BUILDER'},{execution_principal_id:'p',role:'FINAL_AUDITOR'}]),/ROLE_CONFLICT/));
test('Different names same principal blocks',()=>assert.throws(()=>assertPrincipalSeparation([{execution_principal_id:'p',actor:'a',role:'BUILDER'},{execution_principal_id:'p',actor:'b',role:'FINAL_AUDITOR'}]),/ROLE_CONFLICT/));
test('Active Agent PUSH blocks',()=>assert.throws(()=>assertPhaseAActions(['PUSH']),/PROHIBITED/));
test('Unknown write alias blocks',()=>assert.throws(()=>assertPhaseAActions(['ship_changes']),/UNKNOWN_ACTION/));
test('Forged Founder PASS is untrusted',()=>assert.equal(candidateGateClaims({gate:'PASS'})[0].trust,'UNTRUSTED_CANDIDATE_CLAIM'));
test('Founder authorization tied to old Head blocks',()=>assert.throws(()=>validateFounderAuthorization({trust_class:'TRUSTED_GITHUB_RECORD',repository:'o/r',pr_number:148,exact_head:sha('d'),action_type:'GOVERNANCE_PASS',founder_github_identity:'f',trusted_evidence_source:'review:1',issued_at:'2026-08-05T00:00:00Z',revoked:false},{repository:'o/r',prNumber:148,head:sha('b')}),/IDENTITY_MISMATCH/));
