include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unused_import: ignore

linter:
  rules:
    prefer_const_constructors: true
    use_super_parameters: true
    unnecessary_this: false
